name: Run Code Coverage
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Display all files
        run: |
          echo ls -lah

